### PR TITLE
Build SDK with Gradle and publish to Bintray #1 #3

### PR DESCRIPTION
**Pull request by youribonnaffe**
Now using Gradle to build the SDK thus making the external dependencies clear
- Moved sources according the default project layout (src/main/java, src/test/java)
- Added Gradle wrapper
- Removed old libraries in lib/
- Removed old Netbeans configuration files (an Gradle import from the IDE should
be enough)
- Updated Readme to reflect Maven and Gradle coordinates (will be effective once
published on jCenter and Maven central)
- Had to remove Communication field that was still used in tests

com.mangopay.core.ApiPayInsTest#test_PayIns_Create_PayPalWeb is still failing
it seems paypal payins have been removed (at least in the released JAR but not
in the actual code)

The test com.mangopay.core.ApiDisputesTest#test_ResubmitDispute fails too but it seems
to be related to the way the test is built from the comments.

It looks like a lot of changes but I mostly removed and moved files. The only edits are
in the test code, Readme and build files.

The next step would be to create an account on https://bintray.com/ as MangoPay to publish the artifact
there with the command `BINTRAY_USER=mangopay BINTRAY_KEY=XXX ./gradlew clean bintrayUpload` (do not forget to build with a JDK7).

Then the uploaded artifacts can be published via the web interface and you should also require publishing to jCenter and Maven central (ideally for Maven users but jCenter would already be great).
https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html
https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

### CODE REVIEW

**Comment by hobailey** [comment]
Thanks so much for this @youribonnaffe. We're reviewing this and will get back to you shortly, but it's a huge help, so thank you for your efforts :-)

**Comment by hobailey** [comment]
@youribonnaffe - sorry for the delay getting back to you. We're now happy to merge this, however since your PR, we've merged in some other branches (with new functionality - the branches _payin_directdebit_direct_, _client_info_, _mandates_ and _payin_paypal_) which means there are some merge conflicts unfortunately - are you able to update your PR to make the required changes to the new functionality please? Hopefully it shouldn't take too long, but I prefer asking you (rather than doing it myself) since it's originally your changes.

**Comment by youribonnaffe** [comment]
I rebased against the current master and added one commit to set the version to 1.0.7

When I run a `gradle test`a few tests are failing:
- com.mangopay.core.ApiDisputesTest > test_GetFilteredDisputes: Comments are saying you need to create disputes manually
- com.mangopay.core.ApiDisputesTest > test_GetFilteredDisputeDocuments : Comments are saying you need to create disputes manually
- com.mangopay.core.ApiMandatesTest > test_Mandate_Cancel: Comments saying manual debug and user action is required
- com.mangopay.core.ApiPayInsTest > test_PayIns_DirectDebitDirect_Create: Comments saying manual debug and user action is required
- com.mangopay.core.ApiPayInsTest > test_PayIns_Create_PayPalWeb: "The method payment PAYPAL with the ccy EUR is not active for the partner sdk-unit-tests"
- com.mangopay.core.ApiUsersTest > test_Users_GetKycDocument: Pass when ran alone
- com.mangopay.core.ApiUsersTest > test_Users_GetKycDocuments_SortByCreationDate: Pass when ran alone
- com.mangopay.core.ApiWalletsTest > test_Wallets_Create: Pass when ran alone
- com.mangopay.core.ApiWalletsTest > test_Wallets_Transactions: Pass when ran alone
- com.mangopay.core.ApiWalletsTest > test_Wallets_Get FAILED: Pass when ran alone

**Comment by hobailey** [comment]
Brilliant, thanks very much @youribonnaffe for all your work on this :-)
That's fine for those tests.

**Comment by youribonnaffe** [comment]
I noticed you created the versions on bintray but did not upload any files so far. Without those the instructions provided in the Readme won't work.

**Comment by hobailey** [comment]
Yep, we're working on it :-) Should be done this week.

**Comment by hobailey** [comment]
@youribonnaffe perhaps a stupid question, but when you say "files", do we need to upload the whole project or just the JARs for each version?

**Comment by youribonnaffe** [comment]
I would say just the JARs and source JARs

**Comment by hobailey** [comment]
OK, thanks :-)

**Comment by hobailey** [comment]
Hey @youribonnaffe, could you send us an email to support@mangopay.com please - I have a quick question regarding this issue. Thanks.

**Pull request merged**
