### PR TITLE
Fix read Mangopay SDK version properties

### PR DESCRIPTION
**Pull request by blackleg**
I updated a project to 1.3.0 library version, it is working but I receive this exception in the logs.
```
java.io.FileNotFoundException: version.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.mangopay.core.APIs.implementation.OAuthApiImpl.getProjectVersion(OAuthApiImpl.java:66)
22-Feb-2017 09:04:04.714 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
	at com.mangopay.core.APIs.implementation.OAuthApiImpl.createToken(OAuthApiImpl.java:58)
	at com.mangopay.core.AuthorizationTokenManager.getToken(AuthorizationTokenManager.java:39)
	at com.mangopay.core.AuthenticationHelper.getHttpHeaderStrong(AuthenticationHelper.java:61)
	at com.mangopay.core.AuthenticationHelper.getHttpHeaderKey(AuthenticationHelper.java:30)
	at com.mangopay.core.RestTool.getHttpHeaders(RestTool.java:912)
	at com.mangopay.core.RestTool.doRequest(RestTool.java:336)
	at com.mangopay.core.RestTool.request(RestTool.java:142)
	at com.mangopay.core.RestTool.request(RestTool.java:166)
	at com.mangopay.core.APIs.ApiBase.getObject(ApiBase.java:266)
	at com.mangopay.core.APIs.ApiBase.getObject(ApiBase.java:281)
	at com.mangopay.core.APIs.implementation.WalletApiImpl.get(WalletApiImpl.java:33)
```
I make changes in the project to fix this bug and add improvements.

### CODE REVIEW

**Comment by chrissom** [comment]
Any update about this PR?

**Comment by hobailey** [comment]
Thanks very much @blackleg :-)

**Comment by blackleg** [comment]
@hobailey Can you make a new release to fix this issue?

**Comment by chrissom** [comment]
@hobailey same question as @blackleg, can you male a new release to fix this issue?

**Comment by hobailey** [comment]
Sure thing - just done that, so it will be available shortly :-)

**Pull request merged**
