### PR TITLE
Add methods to get transaction status

### PR DESCRIPTION
**Pull request by blackleg**

### CODE REVIEW

**Comment by hobailey** [comment]
Hey @blackleg, could you give some background to the use/need of `setStatus()` please?

**Comment by blackleg** [comment]
I only use the setStatus in the tests, I can remove this.

**Comment by hobailey** [comment]
It's [here](https://github.com/Mangopay/mangopay2-java-sdk/pull/46/files#diff-47b56d29d3517c0ff398df522b43e47dR117) :-)

**Comment by hobailey** [comment]
Thanks @blackleg!

**Pull request merged**
